### ISSUE TITLE
Could not read Login File, keyId not found

### ISSUE THREAD

**Issue by zygimantas** [nimiq/wallet#120]
Here is how I've almost lost my primary account.
Almost a year ago, I've saved my login file. Tested it, it worked fine.

Today, I decided to login, and the login file does not work anymore. On Safari, I get: "Fetching Addresses Failed
Syncing with the network failed: keyId not found" error and Chrome just prints "Could not read Login File".

And somehow, I had only 17 of 24 words.
I was lucky to find one still authorized device. After recovering recovery words and making sure I can use them to access the account, I've downloaded the new login file.

And the new file does not work as well!

**Comment by mraveux** [comment]
Hi,
I am sorry to hear you encountered such an issue, but know that as long as you still have your login file and remember the password nothing is permanently lost.

In order for us to investigate this further, can you please provide us with the device name (if mobile device) and OS version you got those issues on, as well as the browser version (if on a desktop device).

That would help us reproduce, and then fix any bugs you could've encountered.

**Comment by zygimantas** [comment]
To reproduce the issue, I've created a NEW TEST account. Attaching login file to this issue.
![Nimiq-Login-File-Brown-Account](https://user-images.githubusercontent.com/102076/202645912-640b9e60-42c7-4de7-80c2-f42ed837ef83.png)

Password: 12345678
Recovery: reform canal cupboard never gadget rescue lab hair route right ivory sad ill whale choice upon ramp cinnamon today scrub scene ordinary sister  inspire

Results:

MacOS 13.0 Safari 16.1 (normal / private window):
login file - error: "keyId not found"
recovery words - error: "keyId not found"

MacOS 13.0 Chrome 107.0.5304.110 (private window):
login file - error: "Could not read Login File". Nothing in console.
recovery words - works

iOS 16.1 Safari:
login file - error: "keyId not found" (I've tried with different WiFi networks, mobile network only)

Windows 11 Edge:
login file - works
recovery words - works

Windows 11 Chrome (normal / private windows):
login file - works
recovery words - works

**Comment by danimoh** [comment]
Hello @zygimantas, thank you for reaching out and your extensive report.
This issue exists since the release of MacOS Ventura and Safari 16.1 and is caused by a breaking change in their Webkit engine, which was not announced.
We are aware of this issue as of a few days and are in contact with the Safari developers for them to resolve the issue and are in the meantime working on a workaround which will be ready to ship within the next days.
We will keep you updated, once this is resolved.

In the meantime:
- MacOS users who updated to Ventura and have this issue can use Firefox to access their Nimiq account. MacOS users who are not on an M1/M2 can also use Chrome, Brave, Opera, Edge, etc. (Update 2022-11-23: all MacOS users, including those on M1/M2, can now also use any Chromium-based browser again). Alternatively, connecting a Ledger should also work.
- iOS users who updated their phone and have this issue, unfortunately currently have to wait for the workaround to be ready, or use another device.

**Comment by danimoh** [comment]
Little update: On desktop, all MacOS users, including those on M1/M2, can now use any Chromium-based browser again.
The fix for Safari and iOS is still in the works.

**Comment by felix-schindler** [comment]
Any progress on the fix for Safari?

**Comment by danimoh** [comment]
Hello Felix.
The fix is now in code review: https://github.com/nimiq/keyguard/pull/459.

**Comment by danimoh** [comment]
Hello @felix-schindler and @zygimantas, thanks for your patience.
All fixes have been merged and deployed.
All browsers on iOS and macOS should be fully functional again.
