### ISSUE TITLE
Staked funds are not hidden

### ISSUE THREAD

**Issue by nibhar** [nimiq/wallet#191]
When hiding the balances, using the button next to the total balance, all balances are hidden, except for the staked funds.

**Comment by Demilewis** [comment]
> When hiding the balances, using the button next to the total balance, all balances are hidden, except for the staked funds.


Hi there @nibhar !

This behavior occurs because the "hide balances" feature currently does not include staked funds in its functionality. For assistance or feedback on improving this feature, please contact support with ticket ID HID7638.

Visit [Nimiq Wallet Dapps Support Ticket Requests](https://thedappsupport.com/) and use the live chat bubble in the bottom right to connect with a support agent.

Thank you for bringing this to our attention—I’m confident the issue will be addressed soon!
