### ISSUE TITLE
Staking Slider percentage and 'current stake' dot interfere with grid underneath

### ISSUE THREAD

**Issue by julianbauer** [nimiq/wallet#206]
Basically, add a white background behind the circle and numbers so they cover the grid lines underneath

Looks: 
![Image](https://github.com/user-attachments/assets/fda69da1-4bee-4ac1-920f-2a07ebb6b5ca)

Should look:
![Image](https://github.com/user-attachments/assets/afc47cab-ba55-4758-a118-84fca3365df3)

**Comment by mraveux** [comment]
@julianbauer you know we had a white background before and you asked us to remove it, and now you're asking us to add it again. Please do not ask us to remove it again in the future 🙏

**Comment by sisou** [comment]
Now we have a public written record 😏

**Comment by julianbauer** [comment]
Are you sure? Do you remember the reasoning to remove it? Imo not having a background behind the number just looks buggy, can't imagine a reason to not have it in the first place 🧐

**Comment by mraveux** [comment]
I am very sure as I was the one that added it in the first place since it didn't look super nice without, and then was asked to remove it. It was in my mind since then, since it does look "buggy" without it, but I cannot find the exact message about it. (don't remember if it was in person, on slack, notion, figma, etc...)
It was hiding the "previous position" dot and the scale "lines", but it may be that you only wanted to hide the "lines" and not the "dot", and misunderstanding took over. (with me removing it completely)

But in the end it'll take more time talking about it than just making the change again, as it's basically a minute of work. So no worries anyway 😛
