### ISSUE TITLE
Account not synced on re-login

### ISSUE THREAD

**Issue by danimoh** [nimiq/wallet#27]
Steps to reproduce:
- Be logged-in in account A and account B
- Logout from B
- Login into B again
-> The balance and transaction history for B is not being loaded (this is better visible if the accounts share no common transaction history).

**Comment by sisou** [comment]
Does it sync the tx history when switching to account A and back to B?

**Comment by sisou** [comment]
Does it sync on page reload?

**Comment by danimoh** [comment]
On account switch it doesn't sync but on reload.

**Comment by sisou** [comment]
This is because the tx history is only fetched once per account per page load. If logging out and in again in the same page load (session), then it's blocked:

https://github.com/nimiq/wallet/blob/a5764e5a006d21eccf073a7dd1228abf6538b0d5/src/network.ts#L72-L77

A fix for the specific case of logging out would be to remove the addresses of the logged-out account from the `fetchedAddresses` set, so it gets re-triggered afterwards.
